### ISSUE TITLE
Global keyboard shortcuts no longer working

### ISSUE THREAD

**Issue by srk68** [Oery/oery-debouncer#1] opened 2024-11-02 10:51 UTC
Hi,

nice tool and works almost perfectly. However, several global keyboard shortcuts that I defined are no longer working. I am using Ditto Clipboard Manager, and I defined keys CTRL-1, CTRL-2, ... CTRL-0 to quickly access the top 10 saved clipboard history entries. This no longer works as soon as Oery Debouncer is running in the background. Instead of the clipboard entry, the letter "v" is being sent to the application, which is as I guess the leftover of the CTRL-v key combination that Ditto tries to send.

Would be nice if this could be fixed somehow!

**Comment by Oery** [comment] 2024-11-02 23:02
Hey, I don't know why it happens, I can try checking tomorrow but I'm not sure if it could be fixed without rewriting the whole thing.

**Comment by Oery** [comment] 2024-11-05 13:05
I managed to reproduce the issue. I fixed another bug and it fixed it too. You can try the latest release. On my side, Ditto now works as intended. @srk68

**Comment by srk68** [comment] 2024-11-09 09:13
Perfect, nice job! I did not expect an answer this soon so I just checked today, sorry for the delay ;)

**Comment by Oery** [comment] 2024-11-10 00:29
Thanks for the feedback, I will now close the issue as it's fixed.

**Closed as completed by Oery** 2024-11-10 00:29 UTC
